version: "3.8"

services:
  app:
    build: ./backend
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    network_mode: bridge

  neo4j:
    image: neo4j:5.25.1
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    network_mode: bridge
